import numpy as np
def f(num):
    result = [0,1]
    for i in range(num - 2):
        result.append(result[-2]+result[-1])
    return result
print(f(100))
a = np.array(f(100)[-2:-1])
b = np.array(f(100)[-1:])
a,b
a/b
